# Generated by Django 4.2.5 on 2023-09-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_customer_customers_rename_product_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='feature_Products',
            new_name='featured_product_id',
        ),
    ]
