# Generated by Django 4.2.5 on 2023-09-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_feature_products_collections_featured_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='featured_product_id',
            new_name='featured_product',
        ),
    ]
