# Generated by Django 4.2.5 on 2023-09-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_products_orderitems_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='products',
            new_name='product',
        ),
    ]
