# Generated by Django 4.2.5 on 2023-09-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_products_orderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
