# Generated by Django 4.2.5 on 2023-09-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='Customers',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='quantitiy',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='birth_date',
            new_name='brith_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customers',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='quantity',
            new_name='quentity',
        ),
        migrations.RenameIndex(
            model_name='customers',
            new_name='store_Custo_first_n_ec90a0_idx',
            old_name='store_Custo_first_n_d3544d_idx',
        ),
        migrations.AlterField(
            model_name='customers',
            name='membership',
            field=models.CharField(choices=[('MEMBERSHIP_BRONZE', 'Bronze'), ('MEMBERSHIP_SLIVER', 'Silver'), ('MEMBERSHIP_GOLD', 'Gold')], default='B', max_length=17),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAYMENT_STATUS_PENDING', 'P'), ('PAYMENT_STATUS_COMPLETE', 'C'), ('PAYMENT_STATUS_FAILD', 'F')], default='P', max_length=23),
        ),
        migrations.AlterModelTable(
            name='customers',
            table='store_Customerss',
        ),
    ]
