# Generated by Django 4.2.5 on 2023-09-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_customer_address_customers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveIndex(
            model_name='customers',
            name='store_Custo_first_n_ec90a0_idx',
        ),
        migrations.AlterModelTable(
            name='customers',
            table=None,
        ),
    ]
