# Generated by Django 4.2.5 on 2023-09-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_collections_options_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='Products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderItems', to='store.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='collections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.collections'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='store.products')),
            ],
        ),
    ]
