# Generated by Django 4.2.5 on 2023-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitems_products_alter_products_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='describtion',
            field=models.TextField(default='describtions of reviews'),
            preserve_default=False,
        ),
    ]
