# Generated by Django 4.2.5 on 2023-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customers_options_remove_customers_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='brith_date',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='customers',
            name='membership',
            field=models.CharField(choices=[('MEMBERSHIP_BRONZE', 'Bronze'), ('MEMBERSHIP_SILVER', 'Silver'), ('MEMBERSHIP_GOLD', 'Gold')], default='B', max_length=17),
        ),
    ]
