# Generated by Django 4.2.5 on 2023-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_options_rename_customers_order_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
