# Generated by Django 4.2.5 on 2023-09-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
